cmake . -B build-win ^
    -G"Ninja" ^
	-DCMAKE_BUILD_TYPE=Release ^
	-DCMAKE_EXPORT_COMPILE_COMMANDS=ON ^
	-DCMAKE_CXX_COMPILER=g++ ^
	-DCMAKE_C_COMPILER=gcc ^
	-DMSDFGEN_USE_SKIA=OFF -DMSDFGEN_USE_VCPKG=OFF ^
	-DMSDF_ATLAS_NO_ARTERY_FONT=ON ^
	-DMSDF_ATLAS_USE_SKIA=OFF -DMSDF_ATLAS_USE_VCPKG=OFF ^
